# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nihongo no Kana
email: contact@nihongonokana.com
description_fr: > # this means to ignore newlines until "baseurl:"
  Utilisez cette application pour apprendre les bases de l'écriture du japonais.
  Nihongo no Kana vous permet de maîtriser rapidement les 92 signes et leurs dérivés
  appartenant aux deux syllabaires que sont les Hiragana et les Katakana, bases nécessaires 
  pour débuter l'apprentissage de la complexe écriture japonaise.
description_en: > 
  Use this app to learn the basics of japanese writing.
  Nihongo no Kana teaches you how to master quickly the 92 signs and their derivatives
  from the Hiragana and Katakana syllabaries, which are required basics to begin learning
  complexe japanese writing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

# Nihongo no Kana specific settings
current_version: 3.0
store_url: https://itunes.apple.com/[REGION]/app/id525236020
google_analytics: UA-42500159-3

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
